### Env
@base_url=http://localhost:8080

#### @name createAccount
POST {{base_url}}/api/create HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "email@test.com",
    "mobileNumber": "1234567890"
}

### @name getAccount
GET {{base_url}}/api/get?mobileNumber=1234567890 HTTP/1.1
content-type: application/json