### Env
@base_url=http://localhost:8080

#### @name createAccount
POST {{base_url}}/api/create HTTP/1.1
content-type: application/json

{
    "name": "test",
    "email": "email@test.com",
    "mobileNumber": "1234567890"
}

### @name getAccount
GET {{base_url}}/api/get?mobileNumber=1234567890 HTTP/1.1
content-type: application/json

#### @name updateAccount
PUT {{base_url}}/api/update HTTP/1.1
content-type: application/json

{
    "name": "test-user",
    "email": "test@test.com",
    "mobileNumber": "1234567890",
    "accountsDto":{
        "accountNumber": "1167402161",
        "accountType": "current",
        "branchAddress": "changed"
    }
}

### @name deleteAccount
DELETE {{base_url}}/api/delete?mobileNumber=1234567890 HTTP/1.1
content-type: application/json
